#ifndef TASKS_COMMON_H 
#define TASKS_COMMON_H 


#define HTTP_SERVER_TASK_CORE_ID 1 
#define HTTP_SERVER_TASK_PRIORITY 1 
#define HTTP_SERVER_TASK_STACK_SIZE 8192 

#define LINK_RX_QUEUE_DEPTH     16U
#define LINK_RX_TASK_STACK      4096U
#define LINK_APP_TASK_STACK     4096U
#define LINK_RX_TASK_PRIORITY   5U
#define LINK_APP_TASK_PRIORITY  4U

#define SYSTEM_INFO_TASK_STACK 4096U
#define SYSTEM_INFO_TASK_PRIORITY 6

#endif 